#---------------------------------#
#      general configuration      #
#---------------------------------#

branches:
  only:
    - master

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU

configuration: Release

build:
  project: CitpSharp.sln
  
  
#---------------------------------#
#           build events          #
#---------------------------------#
  
before_build:
  - nuget restore

